### ISSUE TITLE
Some of my thoughts

### ISSUE THREAD

**Issue by Lu-Lucifer** [azure06/clips#9]
Hello, 
it is not easy to find many collections, can you add labels to the collection

**Comment by azure06** [comment]
Hi,
That's might be an interesting feature. 
Could you provide a more detailed description in terms of UI/UX?

**Comment by Lu-Lucifer** [comment]
![image](https://user-images.githubusercontent.com/29009277/103114303-f5ef3500-4698-11eb-94f1-0792588da938.png)
when click the star,show the Dialog to choose the collection type
Added the use of favorites type lookup to the search feature

**Comment by azure06** [comment]
I see. Do you have experience with Vue.js?
If you are interested would you mind creating a mock? Especially how would you add the collections/labels?

**Comment by Lu-Lucifer** [comment]
I can try, but it may take some time

**Comment by azure06** [comment]
Got it. Let give it a  try! I will also work on that ;)

**Comment by azure06** [comment]
This feature is now available in 0.1.7 !
